### ISSUE TITLE
JIRA identity updates

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1011]
Adds identity options support for 
- basic auth
- bearer auth

> slucidi  while we're combining the jira server and datacenter options, we should address adding the bearer token auth method
I'd propose we have two identity kinds behind the scenes, basic-auth and bearer. Basic auth would be what we have now, which is a username and password. For Jira Cloud that username I think is always an email, but there's no guarantee of that for on prem.
Bearer would just set the key field on the identity with the bearer token.
For Jira Cloud basic-auth would be the only valid method, but for server/datacenter either basic-auth or bearer could be valid.
For the tracker kind, I suggest we use jira-onprem in place of jira-datacenter and jira-server . (edited)

**Comment by sjd78** [comment]
@ibolton336 Can this issue be closed given issue #1026 was closed with pr #1027 and with pr #1091 pending?

**Comment by ibolton336** [comment]
Yes
