### ISSUE TITLE
App table controls isDeleteEnabled is named wrong

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1030]
Note: This prop is named wrong. It should be named "isDeleteDisabled" which may have resulted in another bug in the job functions page [line 149](https://github.com/konveyor/tackle2-ui/blob/main/client/src/app/pages/controls/job-functions/job-functions.tsx#L149)

**Comment by gildub** [comment]
@ibolton336, although I agree the legacy name is note ideal meanwhile there are few component relying on `AppTableActionButtons`.
Also the Job Function deletion has been fixed with https://github.com/konveyor/tackle2-ui/pull/1032.
