### ISSUE TITLE
[PF5 Regression] - The simple-document-viewer does a "File Upload" on every interaction

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-ui#1134]
Open a simple-document-viewer component and it is not behaving properly.

Easiest is to look as the analysis details for an application:
  - Applicaiton inventory page
  - Analysis tab
  - Open the details drawer for an app with analysis done
  - On the drawer's report tab, find and click the "Analysis details" link
  - The viewer should open correctly
  - Try to open the JSON view, any other action, or click on the code viewer itself

For example:

https://github.com/konveyor/tackle2-ui/assets/3985964/77e90c7f-7c47-475b-9201-6b8af102934f

**Comment by ibolton336** [comment]
[codesandbox here!](https://codesandbox.io/s/react-monaco-editor-forked-9nlrxw?file=/package.json). Is there a scenario where we could remove the empty state to temporarily resolve this? @sjd78

**Comment by gitdallas** [comment]
I have a fix for this on the pf side

**Comment by gitdallas** [comment]
Looks like the latest prerelease of PF should be out with the fix for this.

**Comment by sjd78** [comment]
Resolved with #1203
