### ISSUE TITLE
[PF5 Regression] - Toggle buttons on "Proxy configuration" page don't work

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-ui#1136]
On the Proxy page, the HTTP Proxy and HTTPS Proxy buttons do not toggle when clicked.

**Comment by punithnayak** [comment]
Hey Will work on this issue
![image](https://github.com/konveyor/tackle2-ui/assets/110713318/85b0384a-f96f-4dfb-92a5-e089be324f75)
these buttons ryt?

**Comment by sjd78** [comment]
Resolved by #1230
