### ISSUE TITLE
[PF5 Regression] CodeEditor opens a file browser when clicking anywhere

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1161]
- This bug only happens when a) an emptyState prop is passed to the CodeEditor component & b) Using the prerelease version of PF5 . Codesandbox [here](https://codesandbox.io/s/react-monaco-editor-forked-9nlrxw?file=/package.json)

**Comment by sjd78** [comment]
refinement/duplicate of #1134

**Comment by ibolton336** [comment]
Duplicate of #1134
