### ISSUE TITLE
[PF5 Regression] Application Edit pencils are not available

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-ui#1166]
How it looks now on main:
![image](https://github.com/konveyor/tackle2-ui/assets/3985964/528ff789-3b30-4fc2-b8c6-e180d490cf58)

How it looks running on release-0.2 branch:
![image](https://github.com/konveyor/tackle2-ui/assets/3985964/971de550-f2fe-44df-8f30-c59cd2d856ba)

**Comment by mturley** [comment]
Hm, I had assumed this was an RBAC issue when I noticed the difference between my deployed image and my no-auth local server. Good catch.
