### ISSUE TITLE
Replace deprecated PF dropdown with latest version

### ISSUE THREAD

**Issue by gitdallas** [konveyor/tackle2-ui#1241]
Will require some refactoring. Several use cases of `Dropdown`, `DropdownItem`, `DropdownGroup`, `DropdownToggle` `KebabToggle`, `DropdownToggleCheckbox`

https://www.patternfly.org/components/menus/dropdown

**Comment by mturley** [comment]
@gitdallas Note: I did this in KebabDropdown in https://github.com/konveyor/tackle2-ui/pull/1126 and then had to revert it in https://github.com/konveyor/tackle2-ui/pull/1150. Might be able to start by just reverting that revert.

**Comment by gildub** [comment]
@gitdallas, @mturley, 
I don't see the value to have tackle equivalent of KebabDropdown and if we do it might just make things more complicated to understand, sort of unnecessary complexity. 
What do you guys think ?

**Comment by gitdallas** [comment]
@gildub - it looks like kebab dropdown is used often, so it would reduce some duplicated code.
<img width="333" alt="image" src="https://github.com/konveyor/tackle2-ui/assets/5322142/7aa7eb80-3ea7-4c3a-9729-354f8f603ac5">

**Comment by mturley** [comment]
Yeah I think this may be a case where the PF component is more verbose now for the sake of composability, but that introduces a bunch of repetition if we don't abstract it into our own component. Personally I think it's a good compromise: we can still keep things in our components clean and terse, but we have flexibility to adjust the structure in the future without needing PF changes.

**Comment by gitdallas** [comment]
@gildub  - were you still planning to work on this one?

**Comment by gitdallas** [comment]
i've started now
