### ISSUE TITLE
Update TargetCard to use CardHeader guidelines

### ISSUE THREAD

**Issue by gitdallas** [konveyor/tackle2-ui#1252]
Refactor the TargetCard component a bit, using PF `CardHeader` for header content and checkbox. Show checkbox for both checked and unchecked.

Consider using selectableActions to handle changes - this may or may not make sense in our implementation.

**Comment by sjd78** [comment]
@ibolton336 -- include in work for #1950 ?

**Comment by ibolton336** [comment]
This was fixed in https://github.com/konveyor/tackle2-ui/pull/1251/files

**Comment by ibolton336** [comment]
Changing the line in target-card.tsx 

`    <Card
      onClick={handleCardClick}
       isSelectable={!!cardSelected}`
to 

`    <Card
      onClick={handleCardClick}
       isSelectable={true}`

introduces a nasty PF bug where selecting a card results in triggering the onMove event via a stepChange event being fired. 

Update: event.preventDefault fixed this in the card onClick handler.

**Comment by sjd78** [comment]
Yep, PR #2025 will also resolve this issue.  The `CardHeader.selectableActions` have been aligned and the click handler moved to `onChange` instead of the `Card.onClick`.
