### ISSUE TITLE
Add lock icon for "system" questionnaires 

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1292]
System questionnaires need to have a lock icon as shown in the mocks here:

<img width="1243" alt="Screenshot 2023-08-17 at 10 38 13 AM" src="https://github.com/konveyor/tackle2-ui/assets/11218376/f28572cb-3b88-4fa1-93ea-afa523cc3446">

**Comment by avivtur** [comment]
Hi @ibolton336 
Can I get assigned to this issue?

**Comment by avivtur** [comment]
@ibolton336 Hi
The icon seems to be under the `Name` column but is not aligned with the start of the header, is that on purpose?
![lock-icon-not-aligned](https://github.com/konveyor/tackle2-ui/assets/67270715/a3ecab2b-19e5-450d-9564-40eea5bf3254)

**Comment by ibolton336** [comment]
@avivtur Good question. I would think we want the icon aligned with the header. @justinxhale
