### ISSUE TITLE
Check existing archetypes when starting an app assessment

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1298]
- Wire up check for existing assessments from archetypes when starting an app assessment 
- Add a view assessments action to the assessment modal as shown in the wireframe. It is unclear if accept & view assessments take the user to the same assessment actions page with different state.  TODO: [View assessments page for existing assessments](https://github.com/konveyor/tackle2-ui/issues/1301)

![Image](https://user-images.githubusercontent.com/11218376/262373835-92f9ef0f-25e7-4cd3-9cf4-2130edeebbff.png)

**Comment by ibolton336** [comment]
@justinxhale What happens when a user clicks accept vs View assessments? Shouldn't they both take you to this page: 


![Image](https://github.com/konveyor/tackle2-ui/assets/11218376/97607a32-b48a-42e5-a724-28e7f75b07bb)

**Comment by JustinXHale** [comment]
Kind of. If a user clicks accept, they will start a new assessment so they will see the "Take" button next to the questionnaire. If the were to click View Assessment, those buttons would say "View" and clicking would take them to the questionnaire responses. 
<img width="1500" alt="image" src="https://github.com/konveyor/tackle2-ui/assets/91554933/2939e4a5-3754-4507-b4a2-3603a7dffdd5">
<img width="1500" alt="image" src="https://github.com/konveyor/tackle2-ui/assets/91554933/9a9eef97-8163-4e6d-946b-ae69d6b7e082">
