### ISSUE TITLE
Add Archived assessments / non-required assessments view to assessment actions page

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1300]
![Image](https://user-images.githubusercontent.com/11218376/262376918-402bdabd-4116-4d3b-a243-acd097c91865.png)

This page data is split into two sections: Required & non-required(archived) assessments. Need to decide how to display this data & if we should really have 2 tables or if the archived / required field can just be added to the top table.

**Comment by ibolton336** [comment]
@justinxhale - Could we combine these two sections & add a field indicating if the assessment is required / archived or not?

**Comment by JustinXHale** [comment]
I think the expectation is for this to be 2 seperate tables. Personally I think these being split is cleaner, but a user wont have tons of questionnaires, so having them in a single table and some type of indicator or text that tells the user its archived could be simple.  

We could discuss this in the UI meeting. 
Might have to confirm with @rromannissen here.
