### ISSUE TITLE
Standardize on which form of (byID || byId) to use

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1307]
We aren't consistent about this elsewhere-> we should choose between ...ByID and ...ById and stick with it.

https://stackoverflow.com/questions/15526107/acronyms-in-camelcase

**Comment by sarthaksarthak9** [comment]
@ibolton336 is this issue is still open?

**Comment by ibolton336** [comment]
> @ibolton336 is this issue is still open?

Appears that we have since settled on "ID->Id". There are still a few places where we need to reflect this decision in the code. E.g. getKindIDByRef, useFetchBusinessServiceByID, etc. @sarthaksarthak9

**Comment by sarthaksarthak9** [comment]
@ibolton336 ok!!

**Comment by sarthaksarthak9** [comment]
#1482
