### ISSUE TITLE
`formatPath` helper breaks if some params are substrings of others

### ISSUE THREAD

**Issue by mturley** [konveyor/tackle2-ui#1335]
[The `formatPath` helper found here](https://github.com/konveyor/tackle2-ui/blob/main/client/src/app/Paths.ts#L1), used to interpolate path parameters (`:foo`) in URL strings, has a bug:

```ts
export const formatPath = (path: Paths, data: any) => {
  let url = path as string;

  for (const k of Object.keys(data)) {
    url = url.replace(":" + k, data[k]);
  }

  return url;
};
```

If the URL contains multiple path params that are substrings of each other (like "ruleset" and "rule" in `/issues/all/:ruleset/:rule/affected-applications`), replacing e.g. `:rule` will replace the first half of `:ruleset` as well and result in a malformed URL like `/issues/all/1set/1/affected-applications` . We may want to come back to this and make it use a regex instead (only replace if the placeholder is either followed by a / or is at the end of the string).

[In the Issues page I worked around it](https://github.com/konveyor/tackle2-ui/blob/main/client/src/app/pages/issues/helpers.ts#L116) by including the slashes in my replace string (replace("/:rule/", foo)) but it would be nice to fix `formatPath` and use it there.

**Comment by sjd78** [comment]
This is a great candidate for a set of unit tests!

For example, put the breaking case in there first and then fix up the function so it isn't broke anymore. :wink:
