### ISSUE TITLE
QE requests 9-7-23

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1336]
- Cancel button IDs should all just be 'cancel'. Any more granularity than this causes confusion. 
- Submit button IDs should all just be 'submit'. Any more granularity than this causes confusion. 
- Top table level Kebab ID needs a static ID rather than a PF generated ID for all tables. This one can be table name specific.
- New actions column kebab needs additional selectors. In some cases we are using two actions columns which aren't differentiated by any ID. Worth looking into dropdown options IDs to make sure they are all different for actions columns.
https://docs.google.com/spreadsheets/d/1KkSFQBbyXOh9XA3_u9w26KV1urE317EBeaRgddFgLPE/edit#gid=1625701264

**Comment by gildub** [comment]
@ibolton336, 

Did you mean the "Submit button IDs should all just be 'submit'." ?

**Comment by ibolton336** [comment]
Nailed it! @gildub

**Comment by gildub** [comment]
@ibolton336, who's point of contact for those QE request ?
Is a "selector" an component id used for uniquely identifying element during tests ?

**Comment by ibolton336** [comment]
Try @ibragins . I liked the spreadsheet that might give more info also. Thx.

**Comment by gildub** [comment]
This is now tracked by https://github.com/konveyor/tackle2-ui/issues/443
