### ISSUE TITLE
🐛 Editing an application does not prefill existing tags in the form, so editing and saving removes all tags not added during the edit

### ISSUE THREAD

**Issue by mturley** [konveyor/tackle2-ui#1372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

main

### Priority

Undefined (Default)

### Current Behavior

Find an application in the app inventory page (both tabs) that has tags on it. Use the kebab menu to edit the application, which opens the "update application" modal with most fields prefilled. The tags field is empty. Editing something else in the form and clicking Save updates the application with an empty list of tags (removing the existing tags). Similarly, adding a tag to this field and saving results in the application only having the newly added tag and not the existing tags.

### Expected Behavior

The tags field in the "update application" modal should be pre-filled with the tags that are already present on the application. Submitting the edits should not remove tags that were already present.

### How Reproducible

Always (Default)

### Steps To Reproduce

See above

### Environment

```markdown
- OS:
```

**Comment by sjd78** [comment]
This was fixed over a series of PRs as the same problem was reported in multiple distinct ways:
  - #1403
  - #1408
  - #1427 
  - #1446
  - #1454 
  - #1459

@mturley , @ibolton336 - At this point, I think this PR can be closed as already fixed.

**Comment by mturley** [comment]
Awesome, thanks for following up @sjd78
