### ISSUE TITLE
[TECH DEBT] Leverage react query select field to allow for unique selected answers in questionnaire

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Minor

### Current Behavior

https://github.com/konveyor/tackle2-ui/pull/1430#pullrequestreview-1658800558

### How Reproducible

Other (Add more details in 'Anything else')

### Environment

```markdown
- OS:
```

**Comment by sjd78** [comment]
See https://github.com/konveyor/tackle2-ui/pull/1430#pullrequestreview-1658800558
