### ISSUE TITLE
[BUG] Dependencies Table: Sort stops working after clicking it several times

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/tackle2-ui#1510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.3.0.beta-1.2

### Priority

Critical

### Current Behavior

In the dependencies table, when you have dependencies for multiple applications, and you click the sort button several times, the sort stops working. 

![deps_sort](https://github.com/konveyor/tackle2-ui/assets/9839757/02738a55-11fd-4522-bfa9-70b5a69e669f)

Also, sorting by name doesn't seem to actually sort the deps alphabetically. 

### Expected Behavior

Sorting behavior should be consistent no matter how many times I click it. 

### How Reproducible

Always (Default)

### Steps To Reproduce

- Add following apps to inventory:
    * https://github.com/konveyor/example-applications/tree/main/book-server
    * https://github.com/konveyor/tackle-testapp
    * https://github.com/konveyor/example-applications/tree/main/daytrader
- Run analysis for all these apps using Source + Deps mode. The targets don't really matter, as no matter what targets, the dependencies for an app don't change.
- Go to dependencies view, and click sort several times until it stops working eventually:
![deps_sort](https://github.com/konveyor/tackle2-ui/assets/9839757/9fdb32fa-481c-49c6-92dc-2215887b47a4)

### Environment

```markdown
- OS:
```

**Comment by ibolton336** [comment]
Having trouble reproducing this one locally @pranavgaikwad . Is it consistently failing to sort like this in your env?
