### ISSUE TITLE
0.3.1 priorities

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1672]
- Archetype assessment/Review status components on archetype table
- Bugs around UI  not reflecting required status for questionnaires.
  -   Reports page landscape component
  - Application assessment status improvements. 
    - Need to nail down expectation when application has archetypes when assessments have been completed, but archived. 
    - Application status when ANY application assessment data exists should show application level status rather than archetype inherited status as it does now. 
    - Need to coordinate with HUB to see if improvements can be made to further rely on the assessed boolean from archetypes when questionnaires are all marked as not required. Currently assessed is "true" when this case arises which feels like a bug.
- Application tags dropdown improvements. Need to leverage new PF5 components to allow grouping of tags by category. 
- Have another look at table behavior when data is preloaded for filters from url. Current solution requires some customization that could potentially be baked into the table library. 
- Debug solution refinements for running analysis 
- Chips in sidebar is not sustainable. want a pre-filter for associated archetypes or applications

**Comment by sjd78** [comment]
@ibolton336 -- Can you update this issue based on the current version or close it?
