### ISSUE TITLE
[BUG] Scrollable Modal - Visible Primary and Secondary Button

### ISSUE THREAD

**Issue by JustinXHale** [konveyor/tackle2-ui#1708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

Feb 27, 2024

### Priority

Minor

### Current Behavior

When scrolling in a modal the Primary and Secondary action buttons should always be visible. 
![image](https://github.com/konveyor/tackle2-ui/assets/91554933/0842af22-4554-4b38-83f3-4d2ed9900071)

### Expected Behavior

Primary & Secondary buttons should be visible. [PF Example](https://www.patternfly.org/components/modal/#scrollable-modals)

<img width="624" alt="image" src="https://github.com/konveyor/tackle2-ui/assets/91554933/f750bbef-7ecf-43d2-95aa-5a9271a0a21a">

### How Reproducible

Always (Default)

### Steps To Reproduce

Will apply to ever modal

Modal example
1. Application inventory
2. Create new

### Environment

```markdown
- OS:
```

**Comment by rszwajko** [comment]
@JustinXHale
We have a lot of content inside this modal - it is possible to just pin the buttons as you requested but perhaps it's time to move it to a subpage?
 Quick draft looks the following: [Screencast from 2024-03-13 20-06-35.webm](https://github.com/konveyor/tackle2-ui/assets/64194103/1fd535ec-9b28-44f9-929f-079654b45698)

**Comment by JustinXHale** [comment]
> @JustinXHale We have a lot of content inside this modal - it is possible to just pin the buttons as you requested but perhaps it's time to move it to a subpage? Quick draft looks the following: [Screencast from 2024-03-13 20-06-35.webm](https://github.com/konveyor/tackle2-ui/assets/64194103/1fd535ec-9b28-44f9-929f-079654b45698)

you make a good point. I think this is something we need to look at across the product to make sure everything aligns with the interactions the user expects across the board. Part of me says your right, the other half says though its somewhat long a full page isnt needed b/c the user doesnt actually have to fill in all that information. This is definitely something I will look at as I continue the audit
