### ISSUE TITLE
[BUG] Archetype status for assessment / review missing in archetype table 

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

7.0.2

### Priority

Critical

### Current Behavior

No way to view assessment status for archetype assessments / reviews in the archetype table. 

### Expected Behavior

Would like to see a status text/icon component added for archetypes. 

### How Reproducible

Always (Default)

### Environment

```markdown
- OS:
```

**Comment by sjd78** [comment]
![screenshot-localhost_9000-2024 03 08-11_52_57](https://github.com/konveyor/tackle2-ui/assets/3985964/24c2846c-bd3a-4357-8861-fc3a0e896bf0)

Getting the archetype equivalent of these 2 columns on application table would be quite nice!
