### ISSUE TITLE
Add the ability to individually view all files attached to a task on the Analysis details view

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-ui#1929]
## Summary

For an application, the activity of the current / most recently run analysis task:
  - is viewable in a modal that show the task's activity log in a rich viewer
  - the user may select a merged view, displaying the log merged with all the file attachments
  - the rich viewer display component used allows for code coloring based on a file type we infer

The enhancement will make a few changes:
  1. The activity log view will allow viewing each attached file individually
  2. The activity log view will be moved a full page view

Enhancements reference:
  - https://github.com/konveyor/enhancements/issues/159 
  - https://github.com/konveyor/enhancements/pull/180

### Viewing each file individually

Existing functionality to keep:
  - The default view will be the task's log in yaml format
  - The format may be changed by clicking on the "JSON" tab on the top right
  - The default task log view may be displayed with all attached log files merged into the activity log block by selecting the "Merged" checkbox

Allow viewing all of the task's attached files by adding a select box to the top of the viewer.  The select box should:
  - List the files attached to the task
  - Allow selection of the file and loading it into the view
  - Allow selection of the default task log view

Additional functionality:
  - When an attached file is selected, the text formatting should be switched to "plain text"
  - A few well known file extensions could be detected and the language formatting loaded into the view (json, yaml).  However, this is not required in this enhancement and extra formatting can be added in future as the kinds of attachments are better known.

### View moved to a full page

The current view opens in a modal window.  In order to have more screen space to view the logs and provide selection of attached files, move the view from the modal to a full page.

  - Existing links remain and open the new page
  - The new page does not need an entry on the left nav
  - The URL for the new page should allow for the main left nav to retain focus (e.g. `/applications/123/task-view/456`)
  - Breadcrumbs on the new page should allow for easy navigation back to the previous page and show what application and task is being displayed
  - Note: Future work will be done where the user will have a distinction between different task types (e.g. analysis and language detection) so the breadcrumbs should consider this.

Some potential examples of the bread crumbs (including some potential future uses):
  - [Applications]() > Bear > [Analysis Details]()
  - [Applications]() > Bear > [Analysis Details]() > Attachment > [konveyor-analyzer.output]()
  - [Applications]() > Bear > [Discovery Details]()
  - [Applications]() > Bear > [Analysis Task]() > Current
  - [Applications]() > Bear > [Analysis Task]() > May 31 (123)

### Current State
Open the view from the kebab menu:
![screenshot-localhost_9000-2024 05 31-10_04_57](https://github.com/konveyor/tackle2-ui/assets/3985964/6f50f3c7-2a3a-4093-8a7b-70f90312068d)

Open the view from the application details drawer report tab:
![screenshot-localhost_9000-2024 05 31-10_06_28](https://github.com/konveyor/tackle2-ui/assets/3985964/dc832a17-9f1e-4110-8f8f-d1438066fd5b)

View an analysis details (task activity log):
![screenshot-localhost_9000-2024 05 31-10_06_03](https://github.com/konveyor/tackle2-ui/assets/3985964/772b1bbd-197c-4304-a8f2-7e0b88d6e2d5)

### Future State Mockups
Attached file list box and on page view:
![analysis-details-on-page](https://github.com/konveyor/tackle2-ui/assets/3985964/a13b074a-76af-43ce-9814-60d030c765a9)

Attached file list box opened to select a different file to view:
![analysis-details-select-expanded](https://github.com/konveyor/tackle2-ui/assets/3985964/2d2df37f-ee75-4f9a-93bc-f386628015c4)

Viewing an attached file:
![analysis-details-log](https://github.com/konveyor/tackle2-ui/assets/3985964/2ff558e7-2001-4020-b2e0-05242bc66ee7)

**Comment by sjd78** [comment]
@dymurray, @JustinXHale, @rromannissen -- for your consideration

**Comment by JustinXHale** [comment]
Full page looks great.

**Comment by sjd78** [comment]
@jortel, @mansam -- also for your consideration (sorry about the late tags)

**Comment by rszwajko** [comment]
@sjd78 
Regarding bread crumbs: note that according to [PF guidelines ](https://www.patternfly.org/components/breadcrumb/design-guidelines) the last segment (current page) is considered `active` and not styled as a link.
