### ISSUE TITLE
Create a task manager page and table

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-ui#1931]
## Summary

With the addition of [automatic language discovery](https://github.com/konveyor/enhancements/issues/170) and to give the user more insight and control over discovery and analysis tasks, create a new __Task Manager__ page and table.

Enhancement references:
  - https://github.com/konveyor/enhancements/issues/171
  - https://github.com/konveyor/enhancements/issues/170

## Requirements

Base requirements:
  - Navigation to the page is allowed from the left nav as "Task Manager" on the Migration perspective
  - Navigation to the page with filters applied (from at least the application table with the application filter already applied)
  - Standard table functionality with filtering, sorting, pagination and the right side details view tray
  - Each row in the table corresponds to a task in the system

Table columns to initially include at least:
  - Application linked to the Task
  - Task ID
  - Task Kind (analysis, discovery, others?)
  - Task Status (Scheduled, Pending, In progress, Success, Fail, others?)
  - Task Priority
  - User that created the task (this column has no meaning when running auth disabled)

Table filters and sorting to initially include at least:
  - Application name
  - Task id
  - Task kind
  - Task status
  - Task priority
  - User name

Actions that can be performed:
  - Cancel tasks created by the user (tasks created by other users cannot be cancelled)
  - Enable/disable preemption for the task created by the user (preemption allows the task system to cancel a running lower priority task in order to allow the task to run)

Actions that cannot be performed for Tasks:
  - Create a new task.  This must be done through the analysis wizard or similar.
  - Delete a task

## HUB enhancements that may be needed

See konveyor/tackle2-hub#640 for the filtering, sorting and pagination of the tasks endpoint to be used by the table.  This will reduce the number of task activity logs accessed and sent to keep the table performant.

## Mock ups
Base task manager table:
![Task Manager Table](https://github.com/konveyor/tackle2-ui/assets/3985964/5f53f772-71d2-492c-81d2-2af158a3087a)

**Comment by sjd78** [comment]
@dymurray, @JustinXHale, @rromannissen -- for your consideration

**Comment by JustinXHale** [comment]
@sjd78 couple of questions:

1. Will users have BULK Action capabilities? Delete/Cancel mainly. 
2. What are the priority levels? Low-High, 1-100?

**Comment by sjd78** [comment]
@jortel, @mansam -- also for your consideration (sorry about the late tags)

**Comment by sjd78** [comment]
> @sjd78 couple of questions:
> 
>     1. Will users have BULK Action capabilities? Delete/Cancel mainly.

Good question.  As long as we can do the action individually, we can add the bulk action.

> 
>     2. What are the priority levels? Low-High, 1-100?

https://github.com/konveyor/enhancements/tree/master/enhancements/multiple-provider#task-priority

As of right now, the priority in a number starting a 0 and going up.  I don't know if there is an upper bound.  I also don't know if it makes sense to have a defined "increase / decrease priority 10%" of just a "set priority to this non-negative number" UX.  I kinda like the defined "do this by 10%" kind of operation just to make a user bump their tasks multiple times instead of just bulk setting all of their task priorities to MAX_INT.

@jortel - Thoughts on the priority and the increase or decrease operations?

**Comment by jortel** [comment]
> @sjd78 couple of questions:
> 
> 1. Will users have BULK Action capabilities? Delete/Cancel mainly.

Perhaps not to begin with.

> 2. What are the priority levels? Low-High, 1-100?

0-n low-high.

**Comment by jortel** [comment]
Recommend the column order be:
- id
- application

instead of:
- application
- id

**Comment by rszwajko** [comment]
@jortel @rromannissen 
Do we plan to add date columns (creation/start/end etc) ? I recall such plans being discussed. If we do then remember about new filtering capabilities in this area -> https://github.com/konveyor/tackle2-ui/pull/1913

**Comment by rszwajko** [comment]
@jortel 
I've started tests with the prototype (#1957) - some things don't work for me.  Can you check how they work on your side?

1. sorting seems to work only for `id` field i.e. 
```
// OK 
http://localhost:9000/hub/tasks?sort=desc%3Aid&limit=10&offset=0
//400  i.e. {error: ""state" not supported by sort."}
http://localhost:9000/hub/tasks?sort=asc%3Astate&limit=10&offset=0
```
2. filtering not supported for `createUser` and `id` fields( both listed in the enhancement)
3.  application name is missing in the response and in filtering. Filtering by application ID works but this is not so nice.
4. `priority` is missing in the response and in the filtering
5.  for `kind`  the filtering is supported by the server but it seems it's not included in the response
6. `name`, `locator`, `addon` filtering supported by the server but not included in the enhancement - do we want to add them as optional columns?
