### ISSUE TITLE
Modify application table to better accommodate language discovery and task management

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-ui#1934]
## Summary

With the addition of [automatic language discovery](https://github.com/konveyor/enhancements/issues/170), and [general task management](https://github.com/konveyor/tackle2-ui/issues/1931), the application table needs to be enhanced to give a good overview of an application's status across the various tasks.

Enhancement references:
  - https://github.com/konveyor/enhancements/issues/171
  - https://github.com/konveyor/enhancements/issues/170
  - https://github.com/konveyor/enhancements/issues/155
  - https://github.com/konveyor/enhancements/pull/173 - [enhancement document](https://github.com/konveyor/enhancements/tree/master/enhancements/multiple-provider)

## Requirements

Base requirements:
  - Navigation to and the base functionality of the page and table remains the same (table rows, pagination, sorting, filtering, application bulk actions, application individual actions)
  - The all existing and new status columns are evaluated and refactored to allow easy future modification of the column data sources, calculations, and display
  - The new default set of the table columns fit into the horizontal space of a standard user's display (**TODO**: what is the screen size target?)

Existing columns modified and any new columns created that will provide insight to an application's:
  - **assessment status** (none, inherited, direct, overridden, ...)
  - **review status** (none, inherited, direct, overridden, ...)
  - **analysis status** (none, pending, running, success, fail, ...)
  -  **language discovery status** (none, pending, running, success, fail, result, ...) &rArr; _This column could take many forms and what is actually agreed and built will be decided in the near future. The issue will be updated then._

## HUB enhancements that may be needed
  - Provide an "applications report" endpoint to align data sent to the UI for display with what the UI needs, and have the endpoint calculate status fields instead of replying on the UI to correlate a lot of data across multiple entities.

## Mockups
_(pending further discussions about content, look and feel)_

**Comment by sjd78** [comment]
@dymurray, @JustinXHale, @rromannissen, @jortel, @mansam -- for your consideration

Some of the details will change, but the overall structural work will remain consistent.

**Comment by ibolton336** [comment]
Does this cover any potential wizard changes as well?

**Comment by jortel** [comment]
A technical change:  When creating task resources.
When creating TaskGroup.Addon: analyzer replaced with TaskGroup.Kind: analyzer.

**Comment by sjd78** [comment]
To consider: 
  - Find a superset of values for status states (all states?, assessment/review vs analysis).  Potential base states:
    - None
    - Scheduled
    - Succeeded
    - InProgress
    - Failed
    - _...values for a state inherited from archetype_
    - _...value for "analysis worked before but the latest run failed"_
  - Consider actions that are enabled/disabled based on a status field &rarr; flip that over to the new status states from above

**Comment by sjd78** [comment]
> A technical change: When creating task resources. When creating TaskGroup.Addon: analyzer replaced with TaskGroup.Kind: analyzer.

Handled in #1971

**Comment by sjd78** [comment]
> > Does this cover any potential wizard changes as well?
> 
> I plan on writing another issue just for that change since that work can be done independently.

Handled in #1950

**Comment by JustinXHale** [comment]
Mocks. I would imagine that clicking the popover link takes you to a filter list in the task manager. 

![image](https://github.com/konveyor/tackle2-ui/assets/91554933/827b6fdb-4683-42fd-8bf0-f84ec5dd322d)
![image](https://github.com/konveyor/tackle2-ui/assets/91554933/3ea85885-5ac5-43e8-884b-85a9bfb2d536)

**Comment by sjd78** [comment]
Application icon statuses:
  - Running (InProgressIcon)
  - Success (CheckCircleIcon)
  - Failed (ExclamationCircleIcon)
  - Queued/Pending/In-flight (PendingIcon)
  - No Tasks (not sure on this icon, TaskIcon or UnknownIcon are potentials)

The icon will be driven off looking at the most recent task (by `createTime`) per kind for an application:
  - If there are no tasks for an application, show the application in No Tasks state
  - Else if any are "queued", show the application in Queued state
  - Else if any are "running", show the application in Running
  - Else if any are "failed", show the application as Failed
  - Else if any are "success", show the application as Success

The popover will show the status per task kind and have a link to the task manager page with the application filter already applied.

ref @jortel , @dymurray , @rromannissen
