### ISSUE TITLE
[BUG] `Total Effort` was replaced with `Effort` and cell's data label remained "Total Effort" in Issues -> affected applications

### ISSUE THREAD

**Issue by ibragins** [konveyor/tackle2-ui#1936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Undefined (Default)

### Current Behavior

`Affected applications - sort by Total Effort` test fails because of changed column name - `Total Effort` was replaced with `Effort` and cell's data label remained "Total Effort".

### Expected Behavior

Data label should be aligned with column name

### How Reproducible

Always (Default)

### Environment

```markdown
- OS:
```

**Comment by sjd78** [comment]
This is a follow-up to #1846
