### ISSUE TITLE
Modify analysis wizard to accommodate language discovery

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-ui#1950]
## Summary

With the addition of [automatic language discovery](https://github.com/konveyor/enhancements/issues/170), the analysis wizard target selection step needs to be enhanced.

Enhancement references:
  - https://github.com/konveyor/enhancements/issues/170
  - https://github.com/konveyor/enhancements/issues/155
  - https://github.com/konveyor/enhancements/pull/173 - [enhancement document](https://github.com/konveyor/enhancements/tree/master/enhancements/multiple-provider)

## Requirements

Base requirements:
  - Existing Wizard functionality remains the same
  - On the "Set targets" step:
    - The language selection box needs to be updated to dynamically source the option list, and the selected options
    - The language selection box needs to support an "All Language" and multiple selection of languages
    - The set of target cards displayed will continue to match the selections in the language box
    - Each target card will need a visual indicator of its language/provider
  - When creating the task resources, `TaskGroup.Addon: analyzer` needs to be replaced with `TaskGroup.Kind: analyzer`

Details on changes to the language selection box:
  - Provide a "(Show All)" option to display all targets regardless of language tags
  - Populate the options list from the `Provider` field of the fetched targets.
  - Initially select the languages based on the tags, of tag category "Language", across the applications selected for analysis.

Details on changes to the target cards:
  - Each target card should always display a label with it's provider.  This will allow cards that belong to different providers to be differentiated when more than one language is selected.

## HUB enhancements that may be needed:

None identified initially.  Target data is already available.  Tag category of "Language" is provided in the seed values.  Applications already have their tag data provided.

### Current State
![image](https://github.com/konveyor/tackle2-ui/assets/3985964/3c9aed7f-41af-47ce-9f3f-44c36ffa9f8c)

### Future State
_(the only real difference will be he constant language/provider tag on the cards)_

**Comment by sjd78** [comment]
Note: Until language discovery is working consistently, we can manually tag a language to an application for testing purposes.

**Comment by jortel** [comment]
The application `Analysis` fields used to correlated to task by addon.  This needs to be updated to correlate by kind == analyzer (when not blank) else fallback on addon == analyzer.  The fallback is needed for tasks created in previous releases.
