### ISSUE TITLE
[BUG] Manage columns for "Effort" display in the table view is broken

### ISSUE THREAD

**Issue by kpunwatk** [konveyor/tackle2-ui#1952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

main

### Priority

Major

### Current Behavior

Deselect **Effort** option from Manage columns select options. Check the Effort display in the table view. Effort  column is still shown in Application inventory Table.
[Screencast from 06-11-2024 04:07:41 PM.webm](https://github.com/konveyor/tackle2-ui/assets/87791967/325fabb3-de5d-4aad-be6e-1b67a92d19d5)

### How Reproducible

Always (Default)

### Environment

```markdown
- OS:
```

**Comment by ibolton336** [comment]
Fixed via https://github.com/konveyor/tackle2-ui/pull/1947
