### ISSUE TITLE
Sometimes selectors for DOM objects are not unique

### ISSUE THREAD

**Issue by ibragins** [konveyor/tackle2-ui#198]
Sometimes selectors for objects are not unique and UI automated tests can't figure out which object is needed.
Examples:, 
1.  When configuring proxy - credentials selection both for HTTP and HTTPS are the same
2. Perspective view droplist has all the same selectors as, for example, droplist when creating tags
If I will find anything else - I will add them here as comments

**Comment by ibolton336** [comment]
```
id="https-proxy-credentials-select-toggle"
id="http-proxy-credentials-select-toggle"
```

Looking like this is resolved now @ibragins - Please reopen if you are seeing anything that doesn't look right!
