### ISSUE TITLE
[BUG] Custom migration target: The description textbox exceeds the target card

### ISSUE THREAD

**Issue by mguetta1** [konveyor/tackle2-ui#1981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.5.0-alpha.1

### Priority

Major

### Current Behavior

![Selection_580](https://github.com/konveyor/tackle2-ui/assets/60384172/8883172d-16e2-45fd-8c34-0c54a0a63ece)

### How Reproducible

Always (Default)

### Environment

```markdown
- OS: Fedora 36
- Google Chrome: 126.0.6478.114
```

**Comment by rromannissen** [comment]
Reproduced in 0.5.0-alpha.2
