### ISSUE TITLE
Refactor useServerTasks() hook to allow reuse in both tasks page and tasks drawer

### ISSUE THREAD

**Issue by rszwajko** [konveyor/tackle2-ui#1995]
Remaining part of : https://github.com/konveyor/tackle2-ui/issues/1969
The proposal defined [in this comment](https://github.com/konveyor/tackle2-ui/pull/1955#discussion_r1646592000).

**Comment by sjd78** [comment]
@rszwajko -- I think you may have already handled this in #2004

**Comment by rszwajko** [comment]
> @rszwajko -- I think you may have already handled this in https://github.com/konveyor/tackle2-ui/pull/2004
>
Re-using task actions is a parallel task. My understanding is that under this issue we want to achieve sth similar to [DecoratedApplication](https://github.com/konveyor/tackle2-ui/blob/8ddf4f1523be882a86b07a42ad4b5ec1b8eac11e/client/src/app/pages/applications/applications-table/useDecoratedApplications.ts#L24)

**Comment by rszwajko** [comment]
Task drawer switched to using the infinite scroller pattern which requires a dedicated data source : [`useInfinteServerTasks()`](https://github.com/konveyor/tackle2-ui/blob/1b4a17bafe06107dfa78bc450063f3c4ff6cd1e1/client/src/app/queries/tasks.ts#L92).
Therefore using a common hook is no longer possible.
