### ISSUE TITLE
[BUG] Overflow is missing on the description column from the Archetypes view

### ISSUE THREAD

**Issue by rromannissen** [konveyor/tackle2-ui#1998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.5.0-alpha.2

### Priority

Undefined (Default)

### Current Behavior

Overflow if missing in the description column from the Archetypes view, ellipsis is not displayed and the text is cut instead:

![Screenshot from 2024-07-05 09-57-12](https://github.com/konveyor/tackle2-ui/assets/15966456/457f4f12-b90a-45cd-ae29-69754fc7c2f6)

### Expected Behavior

Ellipsis is displayed on overflow.

### How Reproducible

Always (Default)

### Environment

```markdown
Konveyor 0.5.0-alpha.2
```

**Comment by sjd78** [comment]
Related to #1753
