### ISSUE TITLE
[BUG] Archetype tags should be optional

### ISSUE THREAD

**Issue by rromannissen** [konveyor/tackle2-ui#1999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.5.0-alpha.2

### Priority

Major

### Current Behavior

Archetype tags are mandatory when creating an archetype:

![Screenshot from 2024-07-05 10-09-36](https://github.com/konveyor/tackle2-ui/assets/15966456/2e0f48eb-5c6b-464d-a039-eeb6add14270)

They should be optional instead, as they are expected to be non required additional meta information to add to applications associated to the archetype. Criteria tags are the only ones that should be mandatory, as they define the relationship of an archetype with its associated applications. 

### Expected Behavior

Archetype tags should be optional.

### How Reproducible

Always (Default)

### Environment

```markdown
Konveyor 0.5.0-alpha.2
```

**Comment by sjd78** [comment]
Note: The archetype POST endpoint supports creating an archetype with an empty `tags` prop.
