### ISSUE TITLE
[BUG] More selected languages then available in the Analysis Wizard

### ISSUE THREAD

**Issue by rszwajko** [konveyor/tackle2-ui#2009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.5beta

### Priority

Minor

### Current Behavior

A bug shows 4 languages although only one is available:
![Screenshot from 2024-07-12 13-26-41](https://github.com/user-attachments/assets/554dd70c-cbcd-4db4-8e09-25e8ece8d286)

### Expected Behavior

Only available languages are included.

### How Reproducible

Always (Default)

### Steps To Reproduce

1. use default settings - only Java provider 
2. create an app that uses multiple languages - found on https://github.com/sonatype/nexus-public
3. wait until language discovery finished successfully
4. start Analysis Wizard and go to target selection step

**Comment by sjd78** [comment]
/triage accepted
/priority normal

The count on the select box shows the total number of languages tagged across all selected applications.

The drop down shows the available target languages.

Those numbers will not match if a tag exists that does not have a matching target's language.

The count should be based on the selectable options and not the tag count.
