### ISSUE TITLE
Nit: we should replace the masthead logo with an SVG if we have one

### ISSUE THREAD

**Issue by mturley** [konveyor/tackle2-ui#220]
The current PNG Tackle logo doesn't scale down smoothly on my 1080p monitor. It comes out looking a little blurry:

![Screen Shot 2022-05-13 at 11 33 26 AM](https://user-images.githubusercontent.com/811963/168317762-67bfd4c4-3c11-4362-aaff-2f90fece591f.png)

If we have an SVG version, that would look crisp at any size.

**Comment by ibolton336** [comment]
@mturley Looks like the masthead logo is still a png. Couldn't find an svg version with the white letters in the[ google drive folder](https://drive.google.com/drive/folders/1kO8uwRkw1SlE88V-pif2iF3zAAfIHAaQ). @justinxhale

**Comment by ibolton336** [comment]
![image](https://github.com/konveyor/tackle2-ui/assets/11218376/a2ac7a3e-62d3-4c7d-9692-d45363ad928d)

**Comment by ibolton336** [comment]
Scratch that I found it.
