### ISSUE TITLE
UI Application comment field still checks for 250 char limit

### ISSUE THREAD

**Issue by hjochmann** [konveyor/tackle2-ui#287]
The ui check for editing the comment field still checks for 250 char. Even as the import now allows more the 250 char.

**Comment by khareyash05** [comment]
Hi can I work upon this! I got the solution for this. I took a lorem ipsum of 500 characters and updated the code . Now it's working fine . Here is the screenshot 
![image](https://github.com/konveyor/tackle2-ui/assets/60147732/212e0574-b8d1-48e4-ac49-2a6779a1be98)
