### ISSUE TITLE
Create task management page

### ISSUE THREAD

**Issue by djzager** [konveyor/tackle2-ui#509]
It would be really helpful for the UX of tackle if there were a page dedicated to viewing all Tasks in the hub and expose some basic information like:
 * The application associated with the task
 * The addon being run
 * The secret associated with the task (ie. data for the addon)
 * (maybe) the Volume buckets (application/addon)
 * (Most importantly) the status of the task

**Comment by djzager** [comment]
Waiting for assignment until we agree on what we are talking about doing.

**Comment by sjd78** [comment]
Done in 0.5!

See #1931 and #1934, #1938, #1997
