### ISSUE TITLE
Complete monorepo structure with npm workspace 

### ISSUE THREAD

**Issue by gildub** [konveyor/tackle2-ui#53]
Most of the migration to fully support monorepo has already been done.
It needs to be finished to validate all npm rules and build to work from top level.

Refer to https://github.com/konveyor/tackle2-ui/pull/8

**Comment by ibolton336** [comment]
Another attempt at this was made: https://github.com/konveyor/tackle2-ui/pull/382 

There are a few outstanding issues both locally and downstream that need addressing.

Locally, there is an issue with providing the local ui development env correct paths to the js bundle. 

Downstream, we should be tracking https://issues.redhat.com/browse/CLOUDBLD-11019 for updates

**Comment by gildub** [comment]
Latest attempt is https://github.com/konveyor/tackle2-ui/pull/400
