### ISSUE TITLE
Add test suite that provides regression testing

### ISSUE THREAD

**Issue by dymurray** [konveyor/tackle2-ui#696]
Borrowing the goals from https://github.com/konveyor/tackle2-hub/discussions/241, we want to implement regression testing for the UI. This test suite should provide regression testing for pull requests and release branches. We will likely want to consume and build upon https://github.com/konveyor/tackle-ui-tests.

The details of this suite should be published in enhancements as follow-ups to https://github.com/konveyor/enhancements/pull/98.

**Comment by djzager** [comment]
I believe this could be accomplished by bringing the tackle-ui-tests to this project.

**Comment by sjd78** [comment]
CI testing is now in place for PRs that test:
  - repository level CI (npm build, npm lint, npm test)
  - e2e ui testing at tier0
  - build related file changes to test container image builds

A number of nightly CI jobs are also running.

If another CI test is needed, a new issue for that test should be opened.
