### ISSUE TITLE
Dependencies Table & server side pagination/filter/sort 

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#827]
- Add skeleton for the dependencies table. Using this issue to cover the initial server side filter/sort/pagination
- Add drawer support for dependencies table. This includes the filter toolbar and the query for the list of affected applications. 
![image](https://user-images.githubusercontent.com/11218376/233121700-f80f3d09-9040-4f33-b32d-cd0a558eaa5b.png)
![image](https://user-images.githubusercontent.com/11218376/233121753-9caa64af-0a0c-49ad-ba29-d6e0a64f5d04.png)

**Comment by mturley** [comment]
Nearly closed by #839, I just need to add the drawer to this page and figure out what columns we can display.

**Comment by mturley** [comment]
Not sure how important it is right now to make sure these issues are up to date, but it might be reasonable to move the drawer contents part of this to another issue and mark this one resolved. The drawer contents stuff will need to wait until after Issues stuff is done
