### ISSUE TITLE
Initial status & issue columns need a default value for wave status table

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#905]
![Image](https://github.com/konveyor/tackle2-ui/assets/11218376/d4c0c654-02fd-4595-9a11-762f7360ad5e)

**Comment by gildub** [comment]
@ibolton336 , following the same approach with enhancement documentation and with https://github.com/konveyor/tackle2-ui/issues/911, the section shouldn't show up because there are no section. So it will be blank and no compound area will display when there are no exported application.

**Comment by ibolton336** [comment]
Oh ok. So  what do we show when applications have been assigned to a wave but have not been exported yet? I assume we want a view for this?
