### ISSUE TITLE
Show ticket/issue status as reported from the hub

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#909]
![Image](https://github.com/konveyor/tackle2-ui/assets/11218376/1c817732-d3fe-41c0-8e3d-154673993f95)

**Comment by ibolton336** [comment]
Currently the issue status says creating issue in wave status sub-table, but the hub resource is showing an error.

**Comment by gildub** [comment]
@ibolton336, We must not show an error when status is not on error meanwhile we have to display the error field when status has value "Error" in which case a  (code-block)[https://www.patternfly.org/v4/components/code-block] will be used to display the error which will be triggered by clicking on the error text.
