### ISSUE TITLE
Sidebar falls out of sync when hard navigating to pages outside of the current personas scope

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#954]

**Comment by rszwajko** [comment]
Steps to recreate:
1.  select "Administration" view
2.  navigate directly to a page associated with "Migration" view i.e. `/controls/job-functions`
3. expected results: the sidebar shows "Migration" view as selected view (with corresponding pages)
   actual results: the sidebar for "Administration" view is show (see below)
![image](https://github.com/konveyor/tackle2-ui/assets/64194103/b00439db-c614-4b71-b108-ec3d573731bd)
